import type { Metadata } from "next"
import { Outfit } from "next/font/google"
import "./globals.css"
import ClerkProviderClient from "@/providers/ClerkProvider"
import { ThemeProvider } from "@/providers/themeProvider"

const outfitSans = Outfit({
  variable: "--font-outfit-sans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProviderClient>
      <html lang="en" suppressHydrationWarning>
        <body className={`${outfitSans.variable}  antialiased font-sans`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProviderClient>
  )
}
